p8106-hw1
================
xinran
2/25/2020

# Import data

``` r
train_data = read.csv("./data/solubility_train.csv") %>% 
  janitor::clean_names()
test_data = read.csv("./data/solubility_test.csv") %>% 
  janitor::clean_names()
```

# (a) Fit a linear model using least squares on the training data and calculate the mean square error using the test data.

## Fit linear model on the training data

``` r
fit_lm_tr = lm(solubility ~ .， data = train_data)
summary(fit_lm_tr)
```

    ## 
    ## Call:
    ## lm(formula = solubility ~ ., data = train_data)
    ## 
    ## Residuals:
    ##      Min       1Q   Median       3Q      Max 
    ## -1.75620 -0.28304  0.01165  0.30030  1.54887 
    ## 
    ## Coefficients:
    ##                      Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept)         2.431e+00  2.162e+00   1.124 0.261303    
    ## fp001               3.594e-01  3.185e-01   1.128 0.259635    
    ## fp002               1.456e-01  2.637e-01   0.552 0.580960    
    ## fp003              -3.969e-02  1.314e-01  -0.302 0.762617    
    ## fp004              -3.049e-01  1.371e-01  -2.223 0.026520 *  
    ## fp005               2.837e+00  9.598e-01   2.956 0.003223 ** 
    ## fp006              -6.886e-02  2.041e-01  -0.337 0.735917    
    ## fp007               4.044e-02  1.152e-01   0.351 0.725643    
    ## fp008               1.121e-01  1.636e-01   0.685 0.493331    
    ## fp009              -8.242e-01  8.395e-01  -0.982 0.326536    
    ## fp010               4.193e-01  3.136e-01   1.337 0.181579    
    ## fp011               5.158e-02  2.198e-01   0.235 0.814503    
    ## fp012              -1.346e-02  1.611e-01  -0.084 0.933452    
    ## fp013              -4.519e-01  5.473e-01  -0.826 0.409311    
    ## fp014               3.281e-01  4.550e-01   0.721 0.471044    
    ## fp015              -1.839e-01  1.521e-01  -1.209 0.226971    
    ## fp016              -1.367e-01  1.548e-01  -0.883 0.377340    
    ## fp017              -1.704e-01  1.386e-01  -1.230 0.219187    
    ## fp018              -3.824e-01  2.388e-01  -1.602 0.109655    
    ## fp019              -3.131e-01  3.863e-01  -0.811 0.417862    
    ## fp020               2.072e-01  2.135e-01   0.971 0.332078    
    ## fp021              -5.956e-02  2.632e-01  -0.226 0.821060    
    ## fp022               2.336e-01  3.456e-01   0.676 0.499180    
    ## fp023              -3.193e-01  1.909e-01  -1.672 0.094866 .  
    ## fp024              -4.272e-01  2.827e-01  -1.511 0.131162    
    ## fp025               4.376e-01  4.538e-01   0.964 0.335184    
    ## fp026               2.068e-01  2.564e-01   0.806 0.420273    
    ## fp027               2.424e-01  2.429e-01   0.998 0.318594    
    ## fp028               1.070e-01  1.200e-01   0.892 0.372547    
    ## fp029              -9.857e-02  2.199e-01  -0.448 0.654163    
    ## fp030              -2.361e-01  2.468e-01  -0.957 0.339048    
    ## fp031               8.690e-02  1.346e-01   0.646 0.518754    
    ## fp032              -1.204e+00  7.772e-01  -1.550 0.121628    
    ## fp033               5.766e-01  4.236e-01   1.361 0.173882    
    ## fp034              -1.794e-01  2.618e-01  -0.685 0.493486    
    ## fp035              -2.140e-01  1.704e-01  -1.256 0.209605    
    ## fp036               7.701e-02  1.657e-01   0.465 0.642133    
    ## fp037               1.098e-01  1.725e-01   0.636 0.524693    
    ## fp038               2.721e-01  1.888e-01   1.441 0.150030    
    ## fp039               2.011e-02  2.888e-01   0.070 0.944491    
    ## fp040               5.477e-01  1.890e-01   2.898 0.003873 ** 
    ## fp041              -4.265e-01  3.004e-01  -1.420 0.156143    
    ## fp042              -9.901e-01  7.078e-01  -1.399 0.162294    
    ## fp043              -3.725e-02  2.096e-01  -0.178 0.859011    
    ## fp044              -3.860e-01  2.184e-01  -1.768 0.077562 .  
    ## fp045               2.120e-01  1.299e-01   1.631 0.103238    
    ## fp046              -3.504e-02  2.733e-01  -0.128 0.898010    
    ## fp047              -1.675e-02  1.414e-01  -0.118 0.905775    
    ## fp048               2.610e-01  2.434e-01   1.073 0.283810    
    ## fp049               1.241e-01  1.971e-01   0.630 0.529036    
    ## fp050               9.087e-03  1.410e-01   0.064 0.948648    
    ## fp051               1.050e-01  2.014e-01   0.521 0.602210    
    ## fp052              -4.569e-01  2.482e-01  -1.841 0.066029 .  
    ## fp053               2.994e-01  2.466e-01   1.214 0.225129    
    ## fp054               2.734e-02  1.829e-01   0.149 0.881229    
    ## fp055              -3.662e-01  1.970e-01  -1.858 0.063530 .  
    ## fp056              -2.961e-01  2.979e-01  -0.994 0.320541    
    ## fp057              -1.002e-01  1.379e-01  -0.727 0.467703    
    ## fp058               3.100e-01  8.074e-01   0.384 0.701129    
    ## fp059              -1.615e-01  1.690e-01  -0.956 0.339514    
    ## fp060               2.350e-01  1.474e-01   1.595 0.111209    
    ## fp061              -6.365e-01  1.440e-01  -4.421 1.13e-05 ***
    ## fp062              -5.224e-01  2.961e-01  -1.764 0.078078 .  
    ## fp063              -2.001e+00  1.287e+00  -1.554 0.120553    
    ## fp064               2.549e-01  1.221e-01   2.087 0.037207 *  
    ## fp065              -2.844e-01  1.197e-01  -2.377 0.017714 *  
    ## fp066               2.093e-01  1.264e-01   1.655 0.098301 .  
    ## fp067              -1.406e-01  1.540e-01  -0.913 0.361631    
    ## fp068               4.964e-01  2.028e-01   2.447 0.014630 *  
    ## fp069               1.324e-01  8.824e-02   1.501 0.133885    
    ## fp070               3.453e-03  8.088e-02   0.043 0.965963    
    ## fp071               1.474e-01  1.237e-01   1.192 0.233775    
    ## fp072              -9.773e-01  2.763e-01  -3.537 0.000431 ***
    ## fp073              -4.671e-01  2.072e-01  -2.254 0.024474 *  
    ## fp074               1.793e-01  1.206e-01   1.487 0.137566    
    ## fp075               1.231e-01  1.035e-01   1.188 0.235034    
    ## fp076               5.166e-01  1.704e-01   3.031 0.002525 ** 
    ## fp077               1.644e-01  1.236e-01   1.331 0.183739    
    ## fp078              -3.715e-01  1.588e-01  -2.339 0.019608 *  
    ## fp079               4.254e-01  1.881e-01   2.262 0.023992 *  
    ## fp080               3.101e-01  1.554e-01   1.996 0.046340 *  
    ## fp081              -3.208e-01  1.117e-01  -2.873 0.004192 ** 
    ## fp082               1.243e-01  9.524e-02   1.305 0.192379    
    ## fp083              -6.916e-01  2.134e-01  -3.241 0.001248 ** 
    ## fp084               3.626e-01  2.381e-01   1.523 0.128171    
    ## fp085              -3.310e-01  1.428e-01  -2.317 0.020785 *  
    ## fp086               1.169e-02  9.774e-02   0.120 0.904834    
    ## fp087               4.559e-02  2.797e-01   0.163 0.870568    
    ## fp088               2.416e-01  9.959e-02   2.425 0.015534 *  
    ## fp089               5.999e-01  2.320e-01   2.586 0.009915 ** 
    ## fp090              -2.450e-02  1.154e-01  -0.212 0.831930    
    ## fp091              -2.858e-01  3.185e-01  -0.897 0.369847    
    ## fp092               2.665e-01  2.069e-01   1.288 0.198156    
    ## fp093               1.974e-01  1.087e-01   1.816 0.069803 .  
    ## fp094              -1.991e-01  1.441e-01  -1.381 0.167707    
    ## fp095              -1.403e-01  1.124e-01  -1.248 0.212449    
    ## fp096              -5.024e-01  1.459e-01  -3.445 0.000605 ***
    ## fp097              -2.635e-01  1.666e-01  -1.582 0.114020    
    ## fp098              -2.865e-01  1.633e-01  -1.754 0.079863 .  
    ## fp099               2.592e-01  2.568e-01   1.009 0.313136    
    ## fp100              -4.008e-01  3.034e-01  -1.321 0.186949    
    ## fp101              -1.760e-01  3.019e-01  -0.583 0.560147    
    ## fp102               2.445e-01  3.449e-01   0.709 0.478579    
    ## fp103              -1.493e-01  9.148e-02  -1.632 0.103176    
    ## fp104              -1.428e-01  1.176e-01  -1.214 0.225238    
    ## fp105              -6.912e-02  1.395e-01  -0.495 0.620482    
    ## fp106               1.128e-01  1.288e-01   0.876 0.381495    
    ## fp107               2.778e+00  8.247e-01   3.369 0.000796 ***
    ## fp108               8.836e-03  1.852e-01   0.048 0.961970    
    ## fp109               8.200e-01  2.267e-01   3.617 0.000319 ***
    ## fp110               3.680e-01  3.311e-01   1.111 0.266811    
    ## fp111              -5.565e-01  1.420e-01  -3.918 9.80e-05 ***
    ## fp112              -1.079e-01  2.705e-01  -0.399 0.690108    
    ## fp113               1.511e-01  9.481e-02   1.594 0.111478    
    ## fp114              -1.201e-01  1.891e-01  -0.635 0.525628    
    ## fp115              -1.896e-01  1.405e-01  -1.349 0.177736    
    ## fp116               7.778e-03  1.897e-01   0.041 0.967300    
    ## fp117               2.583e-01  1.779e-01   1.452 0.147070    
    ## fp118              -1.964e-01  1.230e-01  -1.596 0.110940    
    ## fp119               7.515e-01  2.630e-01   2.857 0.004402 ** 
    ## fp120              -1.814e-01  1.794e-01  -1.011 0.312362    
    ## fp121              -4.731e-02  3.957e-01  -0.120 0.904866    
    ## fp122               1.048e-01  1.041e-01   1.007 0.314268    
    ## fp123               3.926e-02  1.765e-01   0.222 0.824066    
    ## fp124               1.235e-01  1.705e-01   0.724 0.469243    
    ## fp125              -2.633e-04  1.151e-01  -0.002 0.998175    
    ## fp126              -2.782e-01  1.177e-01  -2.363 0.018373 *  
    ## fp127              -6.123e-01  1.739e-01  -3.521 0.000457 ***
    ## fp128              -5.424e-01  1.932e-01  -2.807 0.005136 ** 
    ## fp129              -6.731e-02  2.243e-01  -0.300 0.764167    
    ## fp130              -1.034e+00  4.106e-01  -2.518 0.012009 *  
    ## fp131               2.158e-01  1.617e-01   1.335 0.182405    
    ## fp132              -1.976e-01  2.382e-01  -0.830 0.406998    
    ## fp133              -1.573e-01  1.217e-01  -1.293 0.196319    
    ## fp134               2.496e+00  1.196e+00   2.086 0.037310 *  
    ## fp135               1.818e-01  1.319e-01   1.379 0.168460    
    ## fp136              -7.763e-02  3.131e-01  -0.248 0.804237    
    ## fp137              -4.613e-02  2.978e-01  -0.155 0.876947    
    ## fp138              -9.392e-02  1.906e-01  -0.493 0.622251    
    ## fp139               7.659e-02  4.063e-01   0.189 0.850517    
    ## fp140               3.145e-01  2.149e-01   1.463 0.143784    
    ## fp141               2.219e-01  2.765e-01   0.802 0.422532    
    ## fp142               6.272e-01  1.488e-01   4.214 2.83e-05 ***
    ## fp143               9.981e-01  2.929e-01   3.407 0.000692 ***
    ## fp144               2.207e-01  2.839e-01   0.777 0.437195    
    ## fp145              -1.146e-01  1.188e-01  -0.964 0.335169    
    ## fp146              -2.324e-01  2.086e-01  -1.114 0.265716    
    ## fp147               1.502e-01  1.228e-01   1.223 0.221703    
    ## fp148              -1.600e-01  1.319e-01  -1.213 0.225560    
    ## fp149               1.172e-01  1.650e-01   0.710 0.477770    
    ## fp150               9.046e-02  1.577e-01   0.574 0.566368    
    ## fp151               2.899e-01  3.120e-01   0.929 0.353202    
    ## fp152              -2.544e-01  2.990e-01  -0.851 0.395087    
    ## fp153              -3.765e-01  2.773e-01  -1.358 0.175029    
    ## fp154              -1.027e+00  2.033e-01  -5.054 5.50e-07 ***
    ## fp155               4.888e-01  2.916e-01   1.676 0.094163 .  
    ## fp156              -3.602e-02  3.636e-01  -0.099 0.921109    
    ## fp157              -4.715e-01  2.468e-01  -1.910 0.056505 .  
    ## fp158               1.669e-02  1.925e-01   0.087 0.930943    
    ## fp159               1.800e-01  2.432e-01   0.740 0.459378    
    ## fp160               1.525e-02  2.177e-01   0.070 0.944155    
    ## fp161              -2.440e-01  1.433e-01  -1.703 0.089063 .  
    ## fp162               4.910e-02  1.859e-01   0.264 0.791710    
    ## fp163               4.785e-01  3.121e-01   1.533 0.125659    
    ## fp164               5.096e-01  1.899e-01   2.684 0.007446 ** 
    ## fp165               5.793e-01  2.146e-01   2.700 0.007103 ** 
    ## fp166              -6.582e-02  2.185e-01  -0.301 0.763293    
    ## fp167              -6.044e-01  2.515e-01  -2.403 0.016502 *  
    ## fp168              -1.187e-01  1.872e-01  -0.634 0.526173    
    ## fp169              -1.705e-01  8.312e-02  -2.051 0.040650 *  
    ## fp170              -7.902e-02  1.560e-01  -0.506 0.612745    
    ## fp171               4.651e-01  1.186e-01   3.922 9.64e-05 ***
    ## fp172              -4.426e-01  2.440e-01  -1.814 0.070120 .  
    ## fp173               4.243e-01  1.657e-01   2.561 0.010634 *  
    ## fp174              -1.010e-01  2.098e-01  -0.481 0.630311    
    ## fp175              -4.657e-02  2.481e-01  -0.188 0.851136    
    ## fp176               9.736e-01  2.644e-01   3.682 0.000249 ***
    ## fp177               1.386e-01  2.393e-01   0.579 0.562538    
    ## fp178               6.497e-02  2.079e-01   0.313 0.754691    
    ## fp179              -3.415e-02  2.232e-01  -0.153 0.878437    
    ## fp180              -7.905e-01  5.523e-01  -1.431 0.152839    
    ## fp181               4.925e-01  3.218e-01   1.531 0.126309    
    ## fp182              -1.124e-01  1.310e-01  -0.858 0.391384    
    ## fp183               2.998e-01  7.143e-01   0.420 0.674836    
    ## fp184               4.876e-01  1.580e-01   3.087 0.002103 ** 
    ## fp185              -3.778e-01  2.037e-01  -1.854 0.064108 .  
    ## fp186              -3.654e-01  1.953e-01  -1.871 0.061710 .  
    ## fp187               4.457e-01  2.682e-01   1.662 0.097015 .  
    ## fp188               1.475e-01  1.258e-01   1.172 0.241519    
    ## fp189              -1.984e-02  3.468e-01  -0.057 0.954384    
    ## fp190               2.629e-01  3.018e-01   0.871 0.383981    
    ## fp191               2.799e-01  1.465e-01   1.911 0.056388 .  
    ## fp192              -2.404e-01  2.751e-01  -0.874 0.382534    
    ## fp193               1.502e-01  1.494e-01   1.005 0.315159    
    ## fp194               8.029e-01  6.379e-01   1.259 0.208566    
    ## fp195               5.967e-02  3.435e-01   0.174 0.862158    
    ## fp196               1.091e-02  2.544e-01   0.043 0.965812    
    ## fp197              -3.736e-02  1.569e-01  -0.238 0.811793    
    ## fp198               1.896e-01  2.665e-01   0.712 0.476893    
    ## fp199              -9.932e-02  1.797e-01  -0.553 0.580702    
    ## fp200              -6.421e-02  2.161e-01  -0.297 0.766462    
    ## fp201              -4.838e-01  1.980e-01  -2.444 0.014771 *  
    ## fp202               5.664e-01  1.869e-01   3.031 0.002527 ** 
    ## fp203               2.586e-01  6.447e-01   0.401 0.688462    
    ## fp204              -1.371e-01  2.543e-01  -0.539 0.590008    
    ## fp205               7.177e-02  1.561e-01   0.460 0.645857    
    ## fp206              -6.769e-02  1.860e-01  -0.364 0.716094    
    ## fp207              -5.538e-03  2.060e-01  -0.027 0.978560    
    ## fp208              -5.338e-01  6.324e-01  -0.844 0.398925    
    ## mol_weight         -1.232e+00  2.296e-01  -5.365 1.09e-07 ***
    ## num_atoms          -1.478e+01  3.473e+00  -4.257 2.35e-05 ***
    ## num_non_h_atoms     1.795e+01  3.166e+00   5.670 2.07e-08 ***
    ## num_bonds           9.843e+00  2.681e+00   3.671 0.000260 ***
    ## num_non_h_bonds    -1.030e+01  1.793e+00  -5.746 1.35e-08 ***
    ## num_mult_bonds      2.107e-01  1.754e-01   1.201 0.229990    
    ## num_rot_bonds      -5.213e-01  1.334e-01  -3.908 0.000102 ***
    ## num_dbl_bonds      -7.492e-01  3.163e-01  -2.369 0.018111 *  
    ## num_aromatic_bonds -2.364e+00  6.232e-01  -3.794 0.000161 ***
    ## num_hydrogen        8.347e-01  1.880e-01   4.439 1.04e-05 ***
    ## num_carbon          1.730e-02  3.763e-01   0.046 0.963335    
    ## num_nitrogen        6.125e+00  3.045e+00   2.011 0.044645 *  
    ## num_oxygen          2.389e+00  4.523e-01   5.283 1.69e-07 ***
    ## num_sulfer         -8.508e+00  3.619e+00  -2.351 0.018994 *  
    ## num_chlorine       -7.449e+00  1.989e+00  -3.744 0.000195 ***
    ## num_halogen         1.408e+00  2.109e+00   0.668 0.504615    
    ## num_rings           1.276e+00  6.716e-01   1.901 0.057731 .  
    ## hydrophilic_factor  1.099e-02  1.137e-01   0.097 0.922998    
    ## surface_area1       8.825e-02  6.058e-02   1.457 0.145643    
    ## surface_area2       9.555e-02  5.615e-02   1.702 0.089208 .  
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 0.5524 on 722 degrees of freedom
    ## Multiple R-squared:  0.9446, Adjusted R-squared:  0.9271 
    ## F-statistic: 54.03 on 228 and 722 DF,  p-value: < 2.2e-16

## Calculate the mean square error using the test data

``` r
pred_lm_tr = predict(fit_lm_tr, test_data)
mse_test = mean((pred_lm_tr - test_data$solubility)^2);mse_test
```

    ## [1] 0.5558898

# (b) Fit a ridge regression model on the training data, with λ chosen by cross-validation. Report the test error

``` r
set.seed(1)
train_data = na.omit(train_data)
x = model.matrix(solubility ~ ., train_data)[, -1]
y = train_data$solubility
ridge_mod = glmnet(x, y, alpha = 0, lambda = exp(seq(-5, 5, length = 500)))
mat_coef = coef(ridge_mod)
dim(mat_coef)
```

    ## [1] 229 500

``` r
# Cross-validation
cv_ridge = cv.glmnet(x, y,
                     alpha = 0,
                     lambda = exp(seq(-5, 5, length = 500)),
                     type.measure = "mse")
plot(cv_ridge)
```

![](p8106-hw1_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
# Trace plot
plot_glmnet(ridge_mod, xvar = "rlambda")
```

![](p8106-hw1_files/figure-gfm/unnamed-chunk-4-2.png)<!-- -->

``` r
# Predict response in final model
best_lambda = cv_ridge$lambda.min; best_lambda
```

    ## [1] 0.06617643

``` r
pred_resp_ridge = predict(ridge_mod, newx = model.matrix(solubility ~ ., test_data)[, -1], s = best_lambda, type = "response"); pred_resp_ridge
```

    ##                1
    ## 1    0.483167756
    ## 2    0.120348521
    ## 3   -0.526900417
    ## 4    0.769027145
    ## 5    0.043332289
    ## 6    1.478864178
    ## 7    0.590728055
    ## 8    0.438705587
    ## 9    0.545609999
    ## 10  -0.608398226
    ## 11  -0.490551208
    ## 12  -1.446749274
    ## 13   0.219012043
    ## 14  -0.117506759
    ## 15  -0.813120331
    ## 16  -0.806422447
    ## 17  -0.280568592
    ## 18   0.125811417
    ## 19   0.521923706
    ## 20  -0.906450329
    ## 21   0.434697889
    ## 22  -0.217228257
    ## 23  -0.638386853
    ## 24  -0.528196716
    ## 25  -1.088004465
    ## 26  -0.190990099
    ## 27  -0.562645866
    ## 28   1.071573627
    ## 29  -1.862310019
    ## 30  -1.104384075
    ## 31  -2.368945196
    ## 32  -0.847824891
    ## 33  -0.739653625
    ## 34  -0.037616120
    ## 35  -0.029009671
    ## 36  -1.116401898
    ## 37   0.427672805
    ## 38  -0.716850693
    ## 39   0.088780818
    ## 40  -0.898465409
    ## 41  -0.687718922
    ## 42  -2.194848618
    ## 43  -1.142000830
    ## 44  -0.005627178
    ## 45  -1.663875099
    ## 46  -0.926631812
    ## 47  -0.755002937
    ## 48  -0.951278553
    ## 49  -0.809108642
    ## 50  -0.846116255
    ## 51  -0.039621104
    ## 52  -1.482672845
    ## 53  -1.522785336
    ## 54  -1.404699072
    ## 55  -1.872078572
    ## 56  -1.358347996
    ## 57  -1.277319150
    ## 58  -1.572751668
    ## 59  -1.837669865
    ## 60  -1.843131397
    ## 61  -0.997060682
    ## 62  -1.361939958
    ## 63  -1.199416413
    ## 64  -1.228500861
    ## 65  -1.260081131
    ## 66  -1.897903365
    ## 67  -2.842673783
    ## 68  -1.970594623
    ## 69  -1.436493517
    ## 70  -2.953377243
    ## 71  -2.145067390
    ## 72  -2.658845730
    ## 73  -1.795274003
    ## 74  -3.125910357
    ## 75  -1.987203065
    ## 76  -2.723985472
    ## 77  -2.596868649
    ## 78  -2.055636742
    ## 79  -1.773777503
    ## 80  -2.282298916
    ## 81  -1.129058916
    ## 82  -1.676123202
    ## 83  -2.270474821
    ## 84  -2.031877659
    ## 85  -1.086220515
    ## 86  -1.513151329
    ## 87  -3.145252500
    ## 88  -2.305489152
    ## 89  -2.118608931
    ## 90  -2.302975527
    ## 91  -1.782255027
    ## 92  -2.179318800
    ## 93  -2.531916967
    ## 94  -1.678040536
    ## 95  -0.546895840
    ## 96  -2.375993846
    ## 97  -1.852769913
    ## 98  -2.258695593
    ## 99  -1.535778607
    ## 100 -2.054717680
    ## 101 -2.035391746
    ## 102 -2.209873123
    ## 103 -2.078294152
    ## 104 -2.382881668
    ## 105 -2.720933425
    ## 106 -2.088193893
    ## 107 -2.354352409
    ## 108 -2.454536197
    ## 109 -3.127736869
    ## 110 -3.252391222
    ## 111 -2.713561777
    ## 112 -3.143711997
    ## 113 -3.081523895
    ## 114 -3.145221125
    ## 115 -2.725744752
    ## 116 -2.591979826
    ## 117 -2.810463612
    ## 118 -2.456630757
    ## 119 -2.924375192
    ## 120 -2.884055615
    ## 121 -2.386771024
    ## 122 -1.295775234
    ## 123 -3.625267098
    ## 124 -2.942760942
    ## 125 -2.889822586
    ## 126 -2.817591424
    ## 127 -3.572806893
    ## 128 -3.075350474
    ## 129 -3.555186808
    ## 130 -2.853046715
    ## 131 -3.044785057
    ## 132 -3.605014554
    ## 133 -2.412340719
    ## 134 -3.668199834
    ## 135 -2.450725864
    ## 136 -3.439097960
    ## 137 -2.543797951
    ## 138 -2.976849577
    ## 139 -2.851334505
    ## 140 -2.344274692
    ## 141 -2.816373245
    ## 142 -2.050963922
    ## 143 -3.538737915
    ## 144 -2.702359523
    ## 145 -3.144700802
    ## 146 -3.475556759
    ## 147 -2.684642504
    ## 148 -3.177984911
    ## 149 -3.508854068
    ## 150 -3.690459657
    ## 151 -1.957852878
    ## 152 -3.177308434
    ## 153 -2.447864055
    ## 154 -3.754974620
    ## 155 -2.983942455
    ## 156 -3.124889479
    ## 157 -4.407244391
    ## 158 -5.017285859
    ## 159 -3.923457838
    ## 160 -4.267511510
    ## 161 -5.505286223
    ## 162 -4.156042079
    ## 163 -3.283566409
    ## 164 -4.639476861
    ## 165 -4.956580579
    ## 166 -3.522095573
    ## 167 -4.679778378
    ## 168 -4.068406963
    ## 169 -4.789340053
    ## 170 -4.581644291
    ## 171 -3.757616990
    ## 172 -3.711984985
    ## 173 -3.540103909
    ## 174 -4.884921016
    ## 175 -4.873734302
    ## 176 -4.061177085
    ## 177 -3.938392111
    ## 178 -4.704097070
    ## 179 -4.404302940
    ## 180 -3.109584180
    ## 181 -4.777975033
    ## 182 -3.775200474
    ## 183 -4.683151879
    ## 184 -4.398928505
    ## 185 -3.936285221
    ## 186 -3.830010198
    ## 187 -4.644743165
    ## 188 -4.964978003
    ## 189 -6.055007154
    ## 190 -5.903407111
    ## 191 -4.368670948
    ## 192 -2.919002546
    ## 193 -4.437564590
    ## 194 -4.796083761
    ## 195 -4.491063266
    ## 196 -4.477868367
    ## 197 -5.657141862
    ## 198 -4.425713616
    ## 199 -4.969992981
    ## 200 -5.287914475
    ## 201 -7.295405225
    ## 202 -6.509629216
    ## 203 -6.266047795
    ## 204 -6.756537056
    ## 205 -5.840793590
    ## 206 -5.831437670
    ## 207 -5.577101304
    ## 208 -5.820972528
    ## 209 -6.893739831
    ## 210 -6.753958536
    ## 211 -7.183896803
    ## 212 -7.002099078
    ## 213 -7.667381047
    ## 214 -7.893062688
    ## 215 -8.517962551
    ## 216 -7.611605543
    ## 217 -0.012825616
    ## 218  0.389732012
    ## 219  0.280582698
    ## 220 -0.118201736
    ## 221 -1.154873024
    ## 222 -0.573962826
    ## 223 -0.935935321
    ## 224 -0.952845038
    ## 225 -2.207491497
    ## 226 -0.883795924
    ## 227 -0.894410532
    ## 228 -0.979240350
    ## 229 -0.477983538
    ## 230 -1.802061322
    ## 231 -1.467378259
    ## 232 -1.442153309
    ## 233 -0.856037553
    ## 234 -0.030896279
    ## 235 -1.459200373
    ## 236 -1.016499710
    ## 237 -3.405641531
    ## 238 -1.640906027
    ## 239 -1.522785336
    ## 240 -1.357808472
    ## 241 -0.566891923
    ## 242 -2.021459340
    ## 243 -1.580486399
    ## 244 -2.339578432
    ## 245 -1.400627463
    ## 246 -0.553345069
    ## 247 -1.438330504
    ## 248 -1.120614172
    ## 249 -1.007756850
    ## 250 -2.144870661
    ## 251 -1.893069440
    ## 252 -2.121182874
    ## 253 -2.504158292
    ## 254 -3.518913344
    ## 255 -2.506865182
    ## 256 -0.996334030
    ## 257 -1.648481835
    ## 258 -1.674181460
    ## 259 -4.302423970
    ## 260 -1.445243333
    ## 261 -2.291602739
    ## 262 -2.375324272
    ## 263 -2.785781635
    ## 264 -3.136885853
    ## 265 -2.382043414
    ## 266 -1.465863252
    ## 267 -2.517278155
    ## 268 -2.157756829
    ## 269 -2.727440831
    ## 270 -2.900266766
    ## 271 -2.715346548
    ## 272 -3.451395890
    ## 273 -3.399079449
    ## 274 -3.682221435
    ## 275 -2.876708038
    ## 276 -3.563850721
    ## 277 -3.579869715
    ## 278 -2.713775142
    ## 279 -3.646609656
    ## 280 -3.160374709
    ## 281 -2.363372391
    ## 282 -3.887819771
    ## 283 -3.604591018
    ## 284 -3.832995387
    ## 285 -3.993706549
    ## 286 -4.355517279
    ## 287 -3.359779473
    ## 288 -3.051254856
    ## 289 -4.180755466
    ## 290 -5.005727363
    ## 291 -4.461275664
    ## 292 -4.334690565
    ## 293 -3.249393322
    ## 294 -4.599149686
    ## 295 -4.265620004
    ## 296 -4.013269895
    ## 297 -4.174398629
    ## 298 -3.923256020
    ## 299 -5.033097619
    ## 300 -5.659974614
    ## 301 -5.427538873
    ## 302 -5.334818091
    ## 303 -6.414739289
    ## 304 -5.542208568
    ## 305 -5.687608863
    ## 306 -6.928879187
    ## 307 -7.423799626
    ## 308 -8.110204580
    ## 309 -8.122797469
    ## 310 -8.437923456
    ## 311 -8.902478354
    ## 312 -7.168782010
    ## 313 -2.031000582
    ## 314 -2.642341349
    ## 315 -4.652387166
    ## 316 -4.342064431

``` r
# MSE
mse_ridge = mean((pred_resp_ridge - test_data$solubility)^2); mse_ridge
```

    ## [1] 0.5123393

Based on the result, the MSE for ridge regression is
0.5123393.

# (c) Fit a lasso model on the training data, with λ chosen by cross-validation. Report the test error, along with the number of non-zero coefficient estimates.

``` r
set.seed(1)
cv_lasso = cv.glmnet(x, y, alpha = 1, lambda = exp(seq(-8, -1, length = 500)))
# Cross-validation
plot(cv_lasso)
```

![](p8106-hw1_files/figure-gfm/unnamed-chunk-5-1.png)<!-- -->

``` r
cv_lasso$lambda.min
```

    ## [1] 0.00475434

``` r
# Trace plot
plot_glmnet(cv_lasso$glmnet.fit)
```

![](p8106-hw1_files/figure-gfm/unnamed-chunk-5-2.png)<!-- -->

``` r
# Predict response in the final model
pred_resp_lasso = predict(cv_lasso, newx = model.matrix(solubility ~ ., test_data)[, -1], s = cv_lasso$lambda.min, type = "response"); pred_resp_lasso
```

    ##               1
    ## 1    0.60449300
    ## 2    0.16381799
    ## 3   -0.45871789
    ## 4    0.72286800
    ## 5   -0.02757212
    ## 6    1.49324790
    ## 7    0.54534612
    ## 8    0.40377238
    ## 9    0.49411750
    ## 10  -0.53390455
    ## 11  -0.40813870
    ## 12  -1.52975416
    ## 13   0.09103909
    ## 14  -0.07971051
    ## 15  -0.72016222
    ## 16  -0.78982541
    ## 17  -0.28097437
    ## 18  -0.01279723
    ## 19   0.97659265
    ## 20  -0.92993002
    ## 21   0.57002715
    ## 22  -0.04497836
    ## 23  -0.58383701
    ## 24  -0.32171417
    ## 25  -0.98493633
    ## 26  -0.16243109
    ## 27  -0.59429769
    ## 28   0.93229289
    ## 29  -1.92886180
    ## 30  -1.17966305
    ## 31  -2.27761645
    ## 32  -0.83967295
    ## 33  -0.76043556
    ## 34  -0.05729938
    ## 35  -0.12120737
    ## 36  -1.14355383
    ## 37   0.58060962
    ## 38  -0.69065536
    ## 39   0.04086580
    ## 40  -0.93540950
    ## 41  -0.70630378
    ## 42  -2.05930440
    ## 43  -1.14045120
    ## 44   0.02718730
    ## 45  -1.73711488
    ## 46  -0.68930544
    ## 47  -0.57895168
    ## 48  -0.88008498
    ## 49  -0.84116097
    ## 50  -1.03146124
    ## 51  -0.27075441
    ## 52  -1.57731926
    ## 53  -1.56778078
    ## 54  -1.38548603
    ## 55  -1.78930630
    ## 56  -1.30472888
    ## 57  -1.36256227
    ## 58  -1.69347011
    ## 59  -1.95038416
    ## 60  -1.70378184
    ## 61  -0.73183079
    ## 62  -1.29805350
    ## 63  -0.82741757
    ## 64  -1.26188640
    ## 65  -1.43700907
    ## 66  -1.94710516
    ## 67  -2.69341223
    ## 68  -2.02805317
    ## 69  -1.39776946
    ## 70  -2.71157364
    ## 71  -2.12507646
    ## 72  -2.76137450
    ## 73  -1.97362661
    ## 74  -2.93846657
    ## 75  -2.00937659
    ## 76  -2.91343776
    ## 77  -2.67043788
    ## 78  -2.07654599
    ## 79  -1.59602018
    ## 80  -2.30971606
    ## 81  -1.05599224
    ## 82  -1.54898432
    ## 83  -2.18530208
    ## 84  -2.08265970
    ## 85  -1.12881121
    ## 86  -1.53158339
    ## 87  -3.00585711
    ## 88  -2.35720464
    ## 89  -2.12736909
    ## 90  -2.33785902
    ## 91  -1.84289728
    ## 92  -2.31333454
    ## 93  -2.66717166
    ## 94  -1.48579337
    ## 95  -0.65575814
    ## 96  -2.55970755
    ## 97  -1.87573730
    ## 98  -2.20639297
    ## 99  -1.51199659
    ## 100 -2.12620912
    ## 101 -2.15823666
    ## 102 -2.15447128
    ## 103 -2.37711770
    ## 104 -2.24889446
    ## 105 -2.80022736
    ## 106 -2.26075455
    ## 107 -2.41824712
    ## 108 -2.50547168
    ## 109 -3.00887249
    ## 110 -3.07967572
    ## 111 -2.82307586
    ## 112 -2.96397903
    ## 113 -3.12003114
    ## 114 -2.82607554
    ## 115 -2.67780023
    ## 116 -2.71702671
    ## 117 -2.85927750
    ## 118 -2.82330528
    ## 119 -2.93691798
    ## 120 -2.77128168
    ## 121 -2.28813502
    ## 122 -1.34548134
    ## 123 -3.34847049
    ## 124 -2.92282402
    ## 125 -2.92883430
    ## 126 -2.90136213
    ## 127 -3.58000698
    ## 128 -3.17740831
    ## 129 -3.47684382
    ## 130 -3.04895259
    ## 131 -3.04578996
    ## 132 -3.51410076
    ## 133 -2.42120242
    ## 134 -3.81011720
    ## 135 -2.68002542
    ## 136 -3.58703587
    ## 137 -2.38277956
    ## 138 -2.99225860
    ## 139 -2.53996820
    ## 140 -2.10928083
    ## 141 -2.90492932
    ## 142 -2.14297821
    ## 143 -3.39778128
    ## 144 -2.69142238
    ## 145 -3.17361360
    ## 146 -3.60073418
    ## 147 -2.68418842
    ## 148 -3.29808749
    ## 149 -3.51548152
    ## 150 -3.70492506
    ## 151 -2.15844756
    ## 152 -3.06843335
    ## 153 -2.35394724
    ## 154 -3.79316934
    ## 155 -3.02807186
    ## 156 -3.03693243
    ## 157 -4.38400911
    ## 158 -4.86427998
    ## 159 -3.86499432
    ## 160 -4.04697463
    ## 161 -5.47171540
    ## 162 -4.09952101
    ## 163 -3.18414818
    ## 164 -4.56412213
    ## 165 -4.83191414
    ## 166 -3.48131514
    ## 167 -4.67779356
    ## 168 -4.03376490
    ## 169 -4.69053984
    ## 170 -4.43540938
    ## 171 -3.89953207
    ## 172 -3.52405776
    ## 173 -3.50499689
    ## 174 -4.97660766
    ## 175 -4.67165670
    ## 176 -4.09705270
    ## 177 -3.96670024
    ## 178 -4.56199269
    ## 179 -4.41601587
    ## 180 -2.94733218
    ## 181 -4.81960199
    ## 182 -3.58553859
    ## 183 -4.62477791
    ## 184 -4.43586770
    ## 185 -3.89360024
    ## 186 -3.69828660
    ## 187 -4.67985460
    ## 188 -4.52868676
    ## 189 -6.02852727
    ## 190 -5.68533354
    ## 191 -4.27250281
    ## 192 -2.96329659
    ## 193 -4.59221765
    ## 194 -4.79589730
    ## 195 -4.65857721
    ## 196 -4.36529900
    ## 197 -5.65401061
    ## 198 -4.40021740
    ## 199 -4.96673440
    ## 200 -4.97242569
    ## 201 -7.12406784
    ## 202 -6.49882893
    ## 203 -6.33726792
    ## 204 -6.79261051
    ## 205 -5.83144420
    ## 206 -5.92968583
    ## 207 -5.29599414
    ## 208 -5.86867342
    ## 209 -7.07357650
    ## 210 -6.77943047
    ## 211 -7.22540166
    ## 212 -7.13632375
    ## 213 -7.66075095
    ## 214 -7.91786422
    ## 215 -8.38096904
    ## 216 -7.65823043
    ## 217 -0.03899753
    ## 218  0.41421401
    ## 219  0.53722881
    ## 220 -0.02764636
    ## 221 -1.18112599
    ## 222 -0.48576825
    ## 223 -0.85808440
    ## 224 -0.84872695
    ## 225 -2.25942298
    ## 226 -0.85008406
    ## 227 -0.87536245
    ## 228 -1.13821808
    ## 229 -0.50659671
    ## 230 -1.93313017
    ## 231 -1.28938539
    ## 232 -1.19667199
    ## 233 -0.90917186
    ## 234 -0.03946006
    ## 235 -1.50090723
    ## 236 -1.27544806
    ## 237 -2.78017737
    ## 238 -1.72176278
    ## 239 -1.56778078
    ## 240 -1.17388373
    ## 241 -0.55654461
    ## 242 -2.17219258
    ## 243 -1.61931929
    ## 244 -2.08309422
    ## 245 -1.33114886
    ## 246 -0.71680586
    ## 247 -1.44638021
    ## 248 -1.20880300
    ## 249 -1.10655509
    ## 250 -2.15045451
    ## 251 -2.13872980
    ## 252 -1.74585932
    ## 253 -2.68867032
    ## 254 -3.21968630
    ## 255 -2.26916866
    ## 256 -1.06583881
    ## 257 -1.51663260
    ## 258 -1.86532754
    ## 259 -4.18371859
    ## 260 -1.61587275
    ## 261 -2.36959174
    ## 262 -2.33196939
    ## 263 -2.97975184
    ## 264 -3.15408665
    ## 265 -2.32945652
    ## 266 -1.93109922
    ## 267 -2.56542932
    ## 268 -2.23421508
    ## 269 -2.74291031
    ## 270 -2.99698367
    ## 271 -2.74931958
    ## 272 -3.59538874
    ## 273 -3.33124690
    ## 274 -3.54954007
    ## 275 -2.88306065
    ## 276 -3.70745640
    ## 277 -3.64125673
    ## 278 -2.71741170
    ## 279 -3.64513030
    ## 280 -3.21975558
    ## 281 -2.20343661
    ## 282 -3.98774226
    ## 283 -3.41900836
    ## 284 -3.88499537
    ## 285 -4.08616173
    ## 286 -4.05409296
    ## 287 -3.17250648
    ## 288 -3.37588017
    ## 289 -4.32343744
    ## 290 -5.01642349
    ## 291 -4.63914506
    ## 292 -4.31132334
    ## 293 -2.98154133
    ## 294 -4.55503181
    ## 295 -4.25737039
    ## 296 -4.12871897
    ## 297 -4.06821150
    ## 298 -4.01624943
    ## 299 -5.00783696
    ## 300 -5.68926180
    ## 301 -5.13338409
    ## 302 -5.36860546
    ## 303 -6.44543510
    ## 304 -5.39193307
    ## 305 -5.75452922
    ## 306 -6.88191408
    ## 307 -7.49918994
    ## 308 -8.16327903
    ## 309 -8.18797805
    ## 310 -8.57271468
    ## 311 -8.93153496
    ## 312 -7.15570236
    ## 313 -2.14273208
    ## 314 -2.52726467
    ## 315 -4.62836488
    ## 316 -4.58608477

``` r
# MSE
mse_lasso = mean((pred_resp_lasso - test_data$solubility)^2); mse_lasso
```

    ## [1] 0.4985083

``` r
# Number of non-zero coefficient estimates
dim(as.matrix(predict(cv_lasso, s = "lambda.min", type = "coefficients")@x))
```

    ## [1] 142   1

Thus, we know the MSE for lasso model is 0.4985083, and the number of
non-zero coefficient estimates is
144.

# (d) Fit a principle component regression model on the training data, with M chosen by cross-validation. Report the test error, along with the value of M selected by cross-validation.

# (e) Briefly discuss the results obtained in (a)∼(d).

# (f) Which model will you choose for predicting solubility?
